FORMAT: 1A
HOST: http://motdgopher.xyz/

# MOTD API

MOTD is a simple API allowing anyone to post a message for the whole world to see.

## MOTD [/motd]

### Get the Current Message of the Day [GET]

+ Response 200 (text/plain)

        How are you today?

## Edit the MOTD [/edit/{message}]

### Set a New Message of the Day

+ Response 200 (text/plain)

        Message updated.
